### ISSUE TITLE
 'EntityModel' object has no attribute 'get_accounts'

### ISSUE THREAD

**Issue by Beachwood619** [elarroba/django-ledger#4]
'EntityModel' object has no attribute 'get_accounts' but IOMixIn requires get_accounts attribute

@jonathandavidlewis

quickstart.quickstart("albertsalazar")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/albertsalazar/AccountantProject/venv/lib/python3.7/site-packages/django_ledger/examples/quickstart.py", line 100, in quickstart
    je_activity='inv')
  File "/home/albertsalazar/AccountantProject/venv/lib/python3.7/site-packages/django_ledger/models/mixins/io.py", line 98, in create_je
    account_models = getattr(self, 'get_accounts')
AttributeError: 'EntityModel' object has no attribute 'get_accounts'

**Comment by elarroba** [comment]
@Beachwood619 Issue has been corrected. You can try again to use the quickstart option or alternatively go on the app and create a new entity. Select the Use QuickStart Data option only.
